server:
    port: 8080
    shutdown: graceful

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:new1234!@localhost:5432/postgres
    # username: postgres
    # password: ********
    pool:
      max-size: 100